### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gudge25** [newfies-dialer/newfies-dialer#54]
Trying to import contacts but got Internal Server Error
where  are logs how i can solve this issue?

[forex2.csv.zip](https://github.com/newfies-dialer/newfies-dialer/files/916465/forex2.csv.zip)

**Comment by areski** [comment]
You should enable the debug to see what is the error, otherwise you can probably find some info in the log.
For your information we don't support the open source version any longer, contact us if you want the latest version https://www.newfies-dialer.org/newfies-dialer-sms-voice-broadcasting-software-changelog/
